name: Codacy Analysis CLI

on:
  push:
    branches: [ "main", "initial-structure" ]
  pull_request:
    branches: [ "main", "initial-structure" ]

jobs:
  codacy-analysis-cli:
    name: Codacy Analysis CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master