name: Alerta Discord

on:
  push:
    branches:
      - initial-structure

jobs:
  message:
    runs-on: ubuntu-latest
    steps:
    - name: Discord Webhook Action
      uses: tsickert/discord-webhook@v7.0.0
      with:
        webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
        content: ${{ github.event.head_commit.message }}
